### ISSUE TITLE
TypeError: dest.on is not a function

### ISSUE THREAD

**Issue by ktk** [zazuko/csv-validate#9]
I:

- check out the repo
- npm i
-  ./bin/csv-validate.js ~/tmp/2021-takeover-annex2.csv

(or any other CSV for that matter)

and I get:

```
 ./bin/csv-validate.js ~/tmp/2021-takeover-annex2.csv
node:internal/streams/readable:692
  dest.on('unpipe', onunpipe);
       ^

TypeError: dest.on is not a function
    at Readable.pipe (node:internal/streams/readable:692:8)
    at Command.<anonymous> (/Users/ktk/workspace/zazuko/csv-validate/bin/csv-validate.js:29:13)
    at Command.listener [as _actionHandler] (/Users/ktk/workspace/zazuko/csv-validate/node_modules/commander/index.js:426:31)
    at Command._parseCommand (/Users/ktk/workspace/zazuko/csv-validate/node_modules/commander/index.js:1002:14)
    at Command.parse (/Users/ktk/workspace/zazuko/csv-validate/node_modules/commander/index.js:801:10)
    at Object.<anonymous> (/Users/ktk/workspace/zazuko/csv-validate/bin/csv-validate.js:44:9)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)

Node.js v18.11.0

```

**Comment by cristianvasquez** [comment]
Fixed
